# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('publication_date', models.DateField(null=True, verbose_name='date published')),
                ('image', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('availability', models.BooleanField(default=False)),
                ('availability_note', models.CharField(max_length=500, null=True)),
                ('store_link', models.CharField(max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volumes.Product')),
            ],
        ),
    ]
