# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0004_auto_20170114_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
