# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0005_auto_20170114_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailer',
            old_name='name',
            new_name='retailer_name',
        ),
        migrations.AddField(
            model_name='retailer',
            name='store_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
