# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0007_auto_20170114_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='store_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='availability',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='store_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
