# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0008_auto_20170114_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
