# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0009_auto_20170115_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store_link',
        ),
    ]
