# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0011_auto_20170115_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='availability',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='retailer_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='store_link',
            field=models.TextField(null=True),
        ),
    ]
