# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0012_auto_20170117_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='availability',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='store_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
