# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0013_auto_20170117_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='retailer_name',
            field=models.CharField(max_length=100),
        ),
    ]
